spring:
  #数据库连接信息
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.kingbase8.Driver
#    url: jdbc:mysql://localhost:3306/db01
    url: jdbc:kingbase8://192.168.10.210:54321/ch-project-yu
#    username: root
    username: system
#    password: abc123
    password: cddpi.com
  #文件上传的配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
#Mybatis配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

#阿里云OSS
aliyun:
  oss:
    endpoint: https://oss-cn-chengdu.aliyuncs.com
    bucketName: kli-aliyun

logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug